---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eac3-converter
  namespace: eac3-converter
  labels:
    app: eac3-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eac3-converter
  template:
    metadata:
      labels:
        app: eac3-converter
    spec:
      containers:
      - name: eac3-converter
        image: simonverbois/eac3-converter:latest
        resources:
          limits:
            cpu: "4"
            memory: "2G"
          requests:
            cpu: "1"
            memory: "512M"
        livenessProbe:
          exec:
            command:
            - pgrep
            - -f
            - main.py
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: cache-volume
          mountPath: /app/cache
        - name: folder1
          mountPath: /app/input/folder1
        - name: folder2
          mountPath: /app/input/folder2

      volumes:
      - name: config-volume
        configMap:
          name: eac3-converter-config
      - name: cache-volume
        persistentVolumeClaim:
          claimName: eac3-converter-cache
      - name: folder1
        hostPath:
          path: /path/to/folder1  # Replace with your host path
          type: Directory
      - name: folder2
        hostPath:
          path: /path/to/folder2  # Replace with your host path
          type: Directory
